### ISSUE TITLE
favourite personal memes appear with "NAN" instead of rating

### ISSUE THREAD

**Issue by NirBenya** [NirBenya/meme-king#32]
<img width="635" alt="screen shot 2018-06-17 at 20 19 35" src="https://user-images.githubusercontent.com/15313208/41510356-ce558cbe-726b-11e8-8f84-1eb0ca42fcf8.png">

**Comment by GalBY** [comment]
issue taken

**Comment by NirBenya** [comment]
This issue is still open

**Comment by danplisetsky** [comment]
issue taken
